DATA:
  TRAIN_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data"
  VAL_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data"
  BATCH_SIZE: 16
  NUM_WORKERS: 1
  PIN_MEMORY: True
  APPEND_VALID_MASK: True
  TARGET_SCALE_FACTOR: 1
  TRAIN_CROP_SIZE: [320,448]
  VAL_CROP_SIZE: [320,448]
  AUGMENTATION:
    USE: True
    PARAMS:
      CROP_SIZE: [320,448]
      TRAINING:
        SPATIAL_AUG_PARAMS: {"min_scale": -0.1, "max_scale": 1.0, "flip": True}
      VALIDATION:
        SPATIAL_AUG_PARAMS: {"aug_prob": 0.0}
        COLOR_AUG_PARAMS: {"aug_prob": 0.0}
        ERASER_AUG_PARAMS: {"aug_prob": 0.0}
OPTIMIZER:
  NAME: Adam
  LR: 0.001
  PARAMS:
    betas: [0.9, 0.999]
    amsgrad: False
SCHEDULER:
  USE: True
  NAME: StepLR
  PARAMS:
    step_size: 10
    gamma: 0.5
CRITERION:
  CUSTOM: True
  NAME: MultiScaleLoss
  PARAMS: 
    weights: [1, 0.5, 0.25, 0.125, 0.0625]
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
TARGET_SCALE_FACTOR: 1
APPEND_VALID_MASK: True
MIXED_PRECISION: False
FREEZE_BATCH_NORM: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  RANK: 0
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 100
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 1
VALIDATE_INTERVAL: 1
VALIDATE_ON: metric
EPOCHS: 200
NUM_STEPS: null
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: 100
  START_EPOCH: null